const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
test('historical strength edits recalculate and persist totals',()=>{const a=app();a.run("records=[{id:1,date:localDate(),name:'训练',minutes:10,sets:1,volume:100,exercises:1,items:[{name:'哑铃划船',type:'weighted',sets:[{done:true,weight:10,reps:10}]}]}]");assert.match(a.run('training()'),/data-edit-record/);assert.equal(a.run("pages.find(p=>p[0]==='training')[1]"),'记录');assert.equal(a.run("updateRecord('1',{name:'修改后',date:localDate(),minutes:'20','weight-0-0':'20','reps-0-0':'12'})"),true);assert.equal(a.run('summary(rangeRecords()).volume'),240);assert.equal(JSON.parse(a.storage.get('nextstep.records'))[0].minutes,20)});
test('sport edits and deletion update totals while failed storage preserves records',()=>{const a=app();a.run("saveSport({sport:'walk',minutes:'30',weight:'70',date:localDate()})");assert.equal(a.run("updateRecord(records[0].id,{name:'快走',date:localDate(),minutes:'60',sport:'walk-brisk',weight:'80'})"),true);assert.equal(a.run('records[0].calories'),384);a.run('recordDeleteDialog(String(records[0].id))');assert.match(a.element('workout-content').innerHTML,/确认删除/);a.context.localStorage.setItem=()=>{throw Error('quota')};assert.equal(a.run('deleteRecord(records[0].id)'),false);assert.equal(a.run('records.length'),1);a.context.localStorage.setItem=(k,v)=>a.storage.set(k,v);assert.equal(a.run('deleteRecord(records[0].id)'),true);assert.equal(a.run('summary(rangeRecords()).minutes'),0)});
function app(initial={}){const elements=new Map();const element=id=>{if(!elements.has(id))elements.set(id,{textContent:'',innerHTML:'',classList:{add(){},remove(){}},addEventListener(){},showModal(){this.open=true},close(){this.open=false}});return elements.get(id)};const storage=new Map(Object.entries(initial).map(([k,v])=>[k,JSON.stringify(v)]));const context=vm.createContext({Date,console,setInterval(){},setTimeout(){},clearTimeout(){},location:{hash:''},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{querySelector:()=>({style:{}}),getElementById:element,addEventListener(){}},window:{addEventListener(){}}});vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../dist/app.js'),'utf8'),context);return {run:code=>vm.runInContext(code,context),context,storage,element}}
test('empty journal uses actual zero values and a single navigation entry',()=>{const a=app();assert.equal(a.run('summary(rangeRecords()).count'),0);assert.equal(a.run("pages.some(p=>p[0]==='trends')"),false);assert.match(a.run('training()'),/还没有训练记录/);assert.doesNotMatch(a.run('training()'),/示例报表|310 kcal/)});
test('summary includes only saved records in current range',()=>{const a=app();a.run("records=[{id:1,date:localDate(),name:'训练',minutes:12,sets:2,volume:800,exercises:1,items:[]},{id:2,date:'2000-01-01',minutes:99,sets:9,volume:999}]");assert.equal(a.run('summary(rangeRecords()).minutes'),12);assert.equal(a.run('summary(rangeRecords()).volume'),800);assert.match(a.run('training()'),/查看详情/);a.run("render('trends')");assert.equal(a.run('currentPage'),'training')});
test('finished workout updates records and trend totals',()=>{const a=app();a.run("saveProfile({...profileDefaults,goal:'增肌',frequency:'每周 3 次',lifestyle:'久坐为主',experience:'刚开始',duration:'30',equipment:'徒手 / 家中',name:'测试',height:'175',weight:'70'});startWorkout();draft.items[0].type='weighted';draft.items[0].sets[0].weight=40;draft.items[0].sets[0].done=true;finishWorkout()");assert.equal(a.run('records.length'),1);assert.equal(a.run('draft'),null);assert.equal(a.run('summary(rangeRecords()).volume'),400);assert.ok(a.storage.has('nextstep.records'))});
test('storage failure retains the complete draft',()=>{const a=app();a.run("saveProfile({...profileDefaults,goal:'增肌',frequency:'每周 3 次',lifestyle:'久坐为主',experience:'刚开始',duration:'30',equipment:'徒手 / 家中',name:'测试',height:'175',weight:'70'});startWorkout();draft.items[0].sets[0].done=true");a.context.localStorage.setItem=()=>{throw Error('quota')};a.run('finishWorkout()');assert.equal(a.run('records.length'),0);assert.equal(a.run('draft.items[0].sets[0].done'),true)});

test('first use prompts setup and settings leave main navigation',()=>{const a=app();assert.equal(a.run('reminderReason'),'first');assert.equal(a.run('pages.length'),3);assert.equal(a.element('workout-dialog').open,true);assert.match(a.run('plan()'),/完善资料并生成计划/)});
test('generation respects equipment, frequency, available time and workload',()=>{const a=app();for(const count of [2,3,4,5]){a.run("saveProfile({...profileDefaults,goal:'增肌',frequency:'每周 3 次',lifestyle:'久坐为主',experience:'刚开始',duration:'30',equipment:'徒手 / 家中',name:'用户',height:'175',weight:'70',frequency:'每周 "+count+" 次',equipment:'哑铃',duration:'20'})");assert.equal(a.run('profile.trainingPlan.days.filter(d=>d.items.length).length'),count);assert.equal(a.run('nextSession().items.length'),3);assert.match(a.run('nextSession().items[0].name'),/哑铃/);assert.equal(a.run('nextSession().items[0].sets'),2)}});
test('profile and plan save together without discarding an active workout',()=>{const a=app();a.run("saveProfile({...profileDefaults,goal:'增肌',frequency:'每周 3 次',lifestyle:'久坐为主',experience:'刚开始',duration:'30',equipment:'徒手 / 家中',name:'用户',height:'175',weight:'70'});startWorkout();draft.items[0].sets[0].done=true;saveProfile({...profileDefaults,goal:'增肌',frequency:'每周 3 次',lifestyle:'久坐为主',experience:'刚开始',duration:'30',equipment:'徒手 / 家中',name:'用户',height:'175',weight:'71',equipment:'健身房'})");assert.equal(a.run('draft.items[0].sets[0].done'),true);assert.equal(a.run('draft.items[0].name'),'椅子深蹲');assert.equal(a.run("nextSession().items.every(e=>e.type==='weighted'&&e.weight>0)"),true);assert.equal(a.run('reminderReason'),'')});
test('invalid or failed profile save does not replace existing plan',()=>{const a=app();assert.equal(a.run("saveProfile({...profileDefaults,goal:'增肌',frequency:'每周 3 次',lifestyle:'久坐为主',experience:'刚开始',duration:'30',equipment:'徒手 / 家中',name:'用户',height:'0',weight:'70'})"),false);a.run("saveProfile({...profileDefaults,goal:'增肌',frequency:'每周 3 次',lifestyle:'久坐为主',experience:'刚开始',duration:'30',equipment:'徒手 / 家中',name:'用户',height:'175',weight:'70'})");a.context.localStorage.setItem=()=>{throw Error('quota')};assert.equal(a.run("saveProfile({...profileDefaults,goal:'增肌',frequency:'每周 3 次',lifestyle:'久坐为主',experience:'刚开始',duration:'30',equipment:'徒手 / 家中',name:'用户',height:'175',weight:'80'})"),false);assert.equal(a.run('profile.weight'),70)});

test('return reminder depends on inactivity rather than profile age',()=>{const profile={name:'用户',height:175,weight:70,updatedAt:Date.now()-90*86400000};assert.equal(app({'nextstep.profile':profile,'nextstep.lastActive':Date.now()-31*86400000}).run('reminderReason'),'return');assert.equal(app({'nextstep.profile':profile,'nextstep.lastActive':Date.now()-86400000}).run('reminderReason'),'')});

test('fresh install has no preset personal data, records or training plan',()=>{const a=app();assert.equal(a.run('records.length'),0);assert.equal(a.run('draft'),null);assert.equal(a.run('profile.trainingPlan'),undefined);assert.equal(a.run("Object.values(profileDefaults).every(v=>v==='')"),true);assert.match(a.element('workout-content').innerHTML,/请选择/)});

test('monthly buckets contain all saved minutes once and stop at month end',()=>{const a=app();a.run("period='month';records=[{date:localDate(rangeStart()),minutes:7,sets:1,volume:0},{date:localDate(),minutes:11,sets:1,volume:0},{date:'2000-01-01',minutes:1000}]");assert.equal(a.run('chartBuckets().reduce((n,b)=>n+b.minutes,0)'),18);assert.equal(a.run('chartBuckets().length'),a.run('Math.ceil(new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate()/7)'));assert.equal(a.run('chartBuckets().at(-1).to'),a.run('localDate(new Date(new Date().getFullYear(),new Date().getMonth()+1,0))'));assert.match(a.run('bars()'),/training-calendar/)});
test('range switch updates statistics without recreating the page or navigation',()=>{const a=app();a.run("render('training')");const original=a.element('app').innerHTML;let focused=false;const card={innerHTML:'',querySelector:()=>({focus:options=>{focused=options.preventScroll}})},metrics={innerHTML:''},rows={innerHTML:''};a.context.document.querySelector=selector=>({'.activity-card':card,'.journal-metrics':metrics,'.journal-period-records':rows}[selector]);a.run("changePeriod('month')");assert.equal(a.element('app').innerHTML,original);assert.match(card.innerHTML,/aria-pressed="true"/);assert.match(rows.innerHTML,/本月训练记录/);assert.ok(metrics.innerHTML);assert.ok(focused);a.run("changePeriod('week')");assert.match(rows.innerHTML,/本周训练记录/)});

test('month calendar has one cell per day and sums daily sessions without example data',()=>{const a=app();a.run("period='month';records=[{date:localDate(),minutes:10,sets:1,volume:0},{date:localDate(),minutes:25,sets:1,volume:0}]");assert.equal(a.run('monthDays().find(d=>d.date===localDate()).count'),2);assert.equal(a.run('monthDays().find(d=>d.date===localDate()).level'),2);assert.equal(a.run('monthDays().reduce((n,d)=>n+d.minutes,0)'),35);assert.equal(a.run("(monthlyCalendar().match(/data-calendar-date=/g)||[]).length"),a.run('monthDays().length'));assert.match(a.run('calendarDetail(localDate())'),/2 次训练 · 35 分钟/)});

test('home prioritizes training before statistics when there is no workout today',()=>{const a=app();a.run("saveProfile({...profileDefaults,name:'用户',height:'175',weight:'70',goal:'增肌',frequency:'每周 3 次',lifestyle:'久坐为主',experience:'刚开始',duration:'30',equipment:'徒手 / 家中'});profile.trainingPlan.days[(new Date().getDay()+6)%7]={name:'今日测试计划',items:nextSession().items}");const html=a.run('today()');assert.ok(html.indexOf('home-workout')<html.indexOf('stats-grid'));assert.match(html,/今日训练内容/);a.run("records=[{date:localDate(),minutes:5,sets:1,volume:0}]");const done=a.run('today()');assert.ok(done.indexOf('stats-grid')<done.indexOf('home-workout'));assert.match(done,/下一次训练/)});
test('training mode selection does not start a timer and free training needs no plan',()=>{const a=app();a.run('workoutModeDialog()');assert.equal(a.run('draft'),null);assert.match(a.element('workout-content').innerHTML,/自由训练/);assert.equal(a.run("startFreeWorkout({exercise:'自选划船',sets:'2',reps:'12',weight:'5'})"),true);assert.equal(a.run('draft.mode'),'free');assert.equal(a.run('draft.items[0].sets.length'),2);assert.ok(a.run('draft.startedAt')>0);a.run("startFreeWorkout({exercise:'自选深蹲',sets:'3',reps:'10',type:'bodyweight',weight:''})");assert.equal(a.run('draft.items.length'),2);a.run('completeSet(0);finishWorkout()');assert.equal(a.run('records[0].mode'),'free');assert.equal(a.run('records[0].name'),'自由训练');assert.equal(a.run('records[0].volume'),0)});
test('rest countdown persists across reload and duplicate completion is ignored',()=>{const a=app();a.run("startFreeWorkout({exercise:'俯卧撑',sets:'2',reps:'10',type:'bodyweight',weight:''});draft.restSeconds=120;completeSet(0)");assert.ok(a.run('draft.restEnd-Date.now()')>118000);assert.ok(a.run('draft.items[0].sets[0].completedAt')>0);const initial=Object.fromEntries([...a.storage.entries()].map(([k,v])=>[k,JSON.parse(v)]));const resumed=app(initial);assert.equal(resumed.run('restEnd'),a.run('draft.restEnd'));resumed.run('completeSet(0)');assert.equal(resumed.run('restEnd'),a.run('draft.restEnd'));assert.equal(resumed.run('draft.items[0].sets[0].done'),true);resumed.run('endRest()');assert.equal(resumed.run('restEnd'),0)});
test('workout elapsed time is measured from explicit start',()=>{const a=app();a.run("startFreeWorkout({exercise:'划船',sets:'1',reps:'10',weight:'5'});draft.startedAt=Date.now()-125000");assert.match(a.run('elapsedText()'),/^00:02:05$/);a.run('completeSet(0);finishWorkout()');assert.equal(a.run('records[0].minutes'),2);assert.ok(a.run('records[0].seconds')>=125);assert.ok(a.run('records[0].endedAt-records[0].startedAt')>=125000)});

test('single set flow displays only one set and transitions through rest to next group',()=>{const a=app();a.run("startFreeWorkout({exercise:'深蹲',sets:'3',reps:'10',type:'bodyweight',weight:''})");assert.match(a.element('workout-content').innerHTML,/1\/3 组/);assert.doesNotMatch(a.element('workout-content').innerHTML,/<table/);assert.equal((a.element('workout-content').innerHTML.match(/data-field="reps"/g)||[]).length,1);a.run('completeSet(0)');assert.match(a.element('workout-content').innerHTML,/休息一下，再继续/);assert.doesNotMatch(a.element('workout-content').innerHTML,/current-weight/);a.run('endRest()');assert.match(a.element('workout-content').innerHTML,/2\/3 组/);a.run('completeSet(1);endRest();completeSet(2)');assert.match(a.element('workout-content').innerHTML,/这次训练感觉怎么样/);assert.equal(a.run('restEnd'),0)});
test('completing the last set of an exercise selects the next pending exercise after rest',()=>{const a=app();a.run("startFreeWorkout({exercise:'动作A',sets:'1',reps:'10',type:'bodyweight',weight:''});startFreeWorkout({exercise:'动作B',sets:'2',reps:'10',type:'bodyweight',weight:''});selectedExercise=0;completeSet(0);endRest()");assert.equal(a.run('selectedExercise'),1);assert.match(a.element('workout-content').innerHTML,/动作B/);assert.match(a.element('workout-content').innerHTML,/1\/2 组/)});
test('failed group save leaves the current group uncompleted',()=>{const a=app();a.run("startFreeWorkout({exercise:'深蹲',sets:'3',reps:'10',type:'bodyweight',weight:''})");a.context.localStorage.setItem=()=>{throw Error('quota')};a.run('completeSet(0)');assert.equal(a.run('draft.items[0].sets[0].done'),false);assert.equal(a.run('restEnd'),0)});

test('rest screen removes more controls and adding thirty seconds persists deadline',()=>{const a=app();a.run("startFreeWorkout({exercise:'深蹲',sets:'2',reps:'10',type:'bodyweight',weight:''})");assert.doesNotMatch(a.element('workout-content').innerHTML,/本组感受|感受与休息设置/);a.run('completeSet(0)');const before=a.run('restEnd');assert.doesNotMatch(a.element('workout-content').innerHTML,/更多操作/);assert.match(a.element('workout-content').innerHTML,/\+30s/);a.run('extendRest()');assert.equal(a.run('restEnd'),before+30000);assert.equal(JSON.parse(a.storage.get('nextstep.draft')).restEnd,before+30000)});
test('overall feedback is requested at finish and saved with a stopped end time',()=>{const a=app();a.run("startFreeWorkout({exercise:'深蹲',sets:'1',reps:'10',type:'bodyweight',weight:''});completeSet(0)");assert.match(a.element('workout-content').innerHTML,/这次训练感觉怎么样/);const stopped=a.run('draft.finishedAt');a.run("draft.feedback='吃力';finishWorkout()");assert.equal(a.run('records[0].feeling'),'吃力');assert.equal(a.run('records[0].endedAt'),stopped)});

test('zero kg weighted sets are rejected while bodyweight sets store no kg',()=>{const a=app();assert.equal(a.run("startFreeWorkout({exercise:'哑铃卧推',sets:'2',reps:'10',weight:'0'})"),false);a.run("startFreeWorkout({exercise:'哑铃卧推',sets:'2',reps:'10',weight:'5'});draft.items[0].sets[0].weight=0;completeSet(0)");assert.equal(a.run('draft.items[0].sets[0].done'),false);a.run('draft.items[0].sets[0].done=true;finishWorkout()');assert.equal(a.run('records.length'),0)});
test('plan reference uses actual previous same-exercise load and catalog fallback is positive',()=>{const a=app();assert.ok(a.run("recommendedWeight({name:'哑铃卧推'}).weight")>0);a.run("records=[{items:[{name:'哑铃卧推',sets:[{weight:12.5,done:true}]}]}]");assert.equal(a.run("recommendedWeight({name:'哑铃卧推'}).weight"),12.5);assert.equal(a.run("makeWorkoutItem({name:'俯卧撑',sets:2}).sets[0].weight"),null)});
test('exercise replacement retains completed sets and changes only remaining work',()=>{const a=app();a.run("startFreeWorkout({exercise:'哑铃卧推',sets:'3',reps:'10',weight:'5'});completeSet(0);endRest();replaceExercise('器械推胸')");assert.equal(a.run('draft.items[0].sets.length'),1);assert.equal(a.run('draft.items[0].sets[0].done'),true);assert.equal(a.run('draft.items[1].name'),'器械推胸');assert.equal(a.run('draft.items[1].sets.length'),2);assert.ok(a.run('draft.items[1].sets[0].weight')>0);assert.doesNotMatch(a.element('workout-content').innerHTML,/更多操作/);assert.match(a.element('workout-content').innerHTML,/长按结束/)});
test('sports calorie estimate scales with duration and weight and persists its basis',()=>{const a=app();assert.equal(a.run("estimatedCalories('surf',60,70)"),210);assert.equal(a.run("estimatedCalories('swim-slow',60,70)"),406);assert.equal(a.run("estimatedCalories('stairs',30,70)"),238);assert.equal(a.run("estimatedCalories('surf',0,70)"),null);assert.equal(a.run("saveSport({sport:'surf',minutes:'60',weight:'70',date:localDate()})"),true);assert.equal(a.run('records[0].calories'),210);assert.equal(a.run('records[0].met'),3);assert.equal(a.run('records[0].sets'),0);assert.equal(a.run('records[0].volume'),0)});

test('hold to end waits for its threshold and short presses can be cancelled',()=>{const a=app();a.run("startFreeWorkout({exercise:'俯卧撑',type:'bodyweight',sets:'2',reps:'10',weight:''});completeSet(0);endRest()");let pending=null;a.context.setTimeout=fn=>{pending=fn;return 1};a.context.clearTimeout=()=>{pending=null};const button={isConnected:true,classList:{add(){},remove(){}}};a.context.holdTestButton=button;a.run('beginEndHold(holdTestButton)');assert.equal(a.run('draft.finishedAt'),undefined);a.run('cancelEndHold()');assert.equal(pending,null);a.run('beginEndHold(holdTestButton)');pending();assert.ok(a.run('draft.finishedAt')>0);assert.match(a.element('workout-content').innerHTML,/这次训练感觉怎么样/)});
test('plan progress excludes sports and free sessions and deduplicates dates',()=>{const a=app();a.run("records=[{date:localDate(),mode:'sport'},{date:localDate(),mode:'free'},{date:localDate(),mode:'plan'},{date:localDate(),mode:'plan'},{date:'2000-01-01',mode:'plan'}]");assert.equal(a.run('weeklyPlanProgress()'),1);a.run("records=[{date:localDate(),mode:'sport'}]");assert.equal(a.run('strengthToday()'),false);assert.equal(a.run('weeklyPlanProgress()'),0)});
test('last group edits preserve timing and undo restores a pending group',()=>{const a=app();a.run("startFreeWorkout({exercise:'哑铃划船',sets:'2',reps:'10',weight:'5'});completeSet(0)");const deadline=a.run('restEnd'),completed=a.run('draft.items[0].sets[0].completedAt');assert.equal(a.run("updateLastSet({weight:'7.5',reps:'12'})"),true);assert.equal(a.run('restEnd'),deadline);assert.equal(a.run('draft.items[0].sets[0].completedAt'),completed);assert.equal(a.run('draft.items[0].sets[0].weight'),7.5);a.context.localStorage.setItem=()=>{throw Error('quota')};assert.equal(a.run('updateLastSet(null,true)'),false);assert.equal(a.run('draft.items[0].sets[0].done'),true);a.context.localStorage.setItem=(k,v)=>a.storage.set(k,v);assert.equal(a.run('updateLastSet(null,true)'),true);assert.equal(a.run('restEnd'),0);assert.equal(a.run('pendingSet().setIndex'),0)});
test('undo final bodyweight group unfreezes feedback without losing start',()=>{const a=app();a.run("startFreeWorkout({exercise:'俯卧撑',sets:'1',reps:'10',type:'bodyweight'});completeSet(0)");const start=a.run('draft.startedAt');assert.equal(a.run("updateLastSet({reps:'15'})"),true);assert.equal(a.run('draft.items[0].sets[0].weight'),null);assert.equal(a.run('updateLastSet(null,true)'),true);assert.equal(a.run('draft.finishedAt'),undefined);assert.equal(a.run('draft.startedAt'),start)});
test('discard retains draft on removal failure and never deletes history',()=>{const a=app();a.run("startFreeWorkout({exercise:'俯卧撑',sets:'2',reps:'10',type:'bodyweight'});records=[{id:1,date:localDate(),name:'旧记录',minutes:10,sets:1,volume:0,exercises:1}]");a.context.localStorage.removeItem=()=>{throw Error('quota')};assert.equal(a.run('discardWorkout()'),false);assert.ok(a.run('draft'));a.context.localStorage.removeItem=k=>a.storage.delete(k);assert.equal(a.run('discardWorkout()'),true);assert.equal(a.run('draft'),null);assert.equal(a.run('records.length'),1);assert.equal(a.storage.has('nextstep.draft'),false)});
test('rest preference persists and active countdown is unchanged',()=>{const a=app();assert.equal(a.run('changeWorkoutRest(120)'),true);a.run("startFreeWorkout({exercise:'俯卧撑',sets:'2',reps:'10',type:'bodyweight'});completeSet(0)");const deadline=a.run('restEnd');assert.equal(a.run('draft.restSeconds'),120);assert.equal(a.run('changeWorkoutRest(180)'),true);assert.equal(a.run('restEnd'),deadline);assert.equal(a.run('changeWorkoutRest(12)'),false);a.context.localStorage.setItem=()=>{throw Error('quota')};assert.equal(a.run('changeWorkoutRest(60)'),false);assert.equal(a.run('draft.restSeconds'),180)});
